name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}

      - name: Build and push Docker image
        continue-on-error: true
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }} || echo "Build finished (log streaming failed)"


      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }} \
            --platform managed \
            --region ${{ secrets.REGION }} \
            --allow-unauthenticated \
            --set-env-vars VITE_ENV=production,VITE_SHOPIFY_DOMAIN="${{ secrets.VITE_SHOPIFY_DOMAIN }}",VITE_SHOPIFY_STOREFRONT_TOKEN="${{ secrets.VITE_SHOPIFY_STOREFRONT_TOKEN }}",VITE_SHOPIFY_API_VERSION="${{ secrets.VITE_SHOPIFY_API_VERSION }}"
